language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get install zookeeper
services:
  - zookeeper
install:
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
before_script:
    - sudo apt-get install redis-server
script:
  - coverage run --source=echidna `which trial` echidna
after_success:
  - coveralls
