language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install zookeeper redis-server
services:
  - zookeeper
  - redis-server
install:
  - "pip install coveralls --use-wheel"
  - "python setup.py install"
script:
  - coverage run --source=echidna `which trial` echidna
after_success:
  - coveralls
